name: pop-tools-docs
channels:
  - conda-forge
  - nodefaults
dependencies:
  - dask
  - fsspec
  - jupyterlab
  - matplotlib
  - myst-nb
  - netcdf4
  - numba
  - pip
  - pooch
  - python=3.8
  - sphinx-book-theme >= 0.0.38
  - sphinx-copybutton
  - watermark
  - xarray
  - xgcm
  - zarr
  - pip:
      - sphinxext-opengraph
      - sphinx-comments
      - -r ../requirements.txt
      - -e ..
