name: Cancel
on:
  workflow_run:
    workflows: ['CI']
    types:
      - requested
jobs:
  cancel:
    name: Cancel previous runs
    runs-on: ubuntu-latest
    steps:
      - uses: styfle/cancel-workflow-action@b173b6ec0100793626c2d9e6b90435061f4fc3e5 #0.11.0
        with:
          workflow_id: ${{ github.event.workflow.id }}
