name: Cancel
on:
  workflow_run:
    workflows: ['CI']
    types:
      - requested
jobs:
  cancel:
    name: Cancel previous runs
    runs-on: ubuntu-latest
    steps:
      - uses: styfle/cancel-workflow-action@0.10.1
        with:
          workflow_id: ${{ github.event.workflow.id }}
