name: Upstream-dev CI
on:
  schedule:
    - cron: "0 0 * * *" # Daily “At 00:00”
jobs:
  upstream-dev:
    name: upstream-dev
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@505e6394dae86d6a5c7fbb6e3fb8938e3e863830 #v3.1.1
        with:
          channels: conda-forge,nodefaults
          channel-priority: strict
          mamba-version: "*"
          activate-environment: pop-tools-dev
          auto-update-conda: false
          python-version: 3.12
          environment-file: ci/environment-upstream-dev.yml
      - name: Install pop-tools
        run: |
          python -m pip install . --no-deps
          conda list
      - name: Run Tests
        run: |
          python -m pytest
