name: CI
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  schedule:
    - cron: '0 0 * * *' # Daily “At 00:00”
  workflow_dispatch: # allows you to trigger manually

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: python-${{ matrix.python-version }}
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.8', '3.11']
    steps:
      - uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@v2
        with:
          channels: conda-forge,nodefaults
          channel-priority: strict
          mamba-version: '*'
          activate-environment: pop-tools-dev
          auto-update-conda: false
          python-version: ${{ matrix.python-version }}
          environment-file: ci/environment.yml

      - name: Install pop-tools
        run: |
          python -m pip install . --no-deps
          conda list

      - name: Run Tests
        run: |
          python -m pytest

      - name: Upload code coverage to Codecov
        uses: codecov/codecov-action@v3.1.4
        with:
          file: ./coverage.xml
          flags: unittests
          env_vars: OS,PYTHON
          name: codecov-umbrella
          fail_ci_if_error: false
